include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    non_constant_identifier_names: ignore
    unused_import: ignore
    deprecated_member_use_from_same_package: ignore