name: lxp_ithub_models
description: Package of data models for the LXP IThub
version: 2.0.0+3
homepage: https://github.com/meg4cyberc4t/lxp_ithub_models

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.1.0+1
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk:  flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  json_serializable: ^6.4.1
