name: lxp_ithub_models
description: Package of data models for the LXP IThub
version: 1.0.1+2
homepage: https://github.com/meg4cyberc4t/lxp_ithub_models

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dart_mappable: ^1.2.0
  flutter:
    sdk: flutter
  freezed: ^2.1.0+1
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk:  flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  dart_mappable_builder: ^1.1.0
  freezed_annotation: ^2.1.0
  json_serializable: ^6.4.1
